fx_version 'cerulean'fx_version 'cerulean'

lua54 'yes'game 'gta5'



game 'gta5'author 'autogenerated'

description 'Minimal qb-weapons stub to satisfy qb-inventory dependency'

name 'qb-weapons'

description 'Minimal qb-weapons stub to satisfy qb-inventory dependency'server_script 'server.lua'


client_scripts {
  'client.lua'
}

server_scripts {
  'server.lua'
}
